# Generated by Django 3.2 on 2021-05-01 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='competitions/')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=30)),
                ('no_of_tickets', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=18, unique=True)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competition')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tickets for different comprtition',
                'db_table': 'tickets',
            },
        ),
    ]
