# Generated by Django 3.2 on 2021-05-01 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=30000),
            preserve_default=False,
        ),
    ]
