# Generated by Django 3.1.7 on 2021-05-06 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_competition_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='ticket_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
