# Generated by Django 3.2 on 2021-05-10 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_competition_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 14, 46, 34, 365961, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
