# Generated by Django 3.2 on 2021-05-11 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_competition_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='question1',
            field=models.CharField(default=django.utils.timezone.now, max_length=30000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='question2',
            field=models.CharField(default=django.utils.timezone.now, max_length=30000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='question3',
            field=models.CharField(default=django.utils.timezone.now, max_length=30000),
            preserve_default=False,
        ),
    ]
