# Generated by Django 3.2 on 2021-05-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210511_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_number',
        ),
    ]
