# Generated by Django 3.2 on 2021-05-12 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_tickets_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'DRAWN')], default=0),
        ),
        migrations.CreateModel(
            name='winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tickets')),
            ],
        ),
    ]
