# Generated by Django 3.2 on 2021-05-18 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_competition_sold_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='image1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='competitions/'),
            preserve_default=False,
        ),
    ]
