# Generated by Django 3.2.3 on 2021-06-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='promos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('validity', models.DateTimeField()),
            ],
        ),
    ]
