# Generated by Django 3.2.3 on 2021-06-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_promos'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
